export default [
  "Amatic SC",
  "Arial",
  "Caveat",
  "Comfortaa",
  "Courier Prime",
  "DM Mono",
  "EB Garamond",
  "Gilda Display",
  "Happy Monkey",
  "Helvetica",
  "Inter",
  "Lobster",
  "Merriweather",
  "Montserrat",
  "Open Sans",
  "Oswald",
  "Playfair Display",
  "Poppins",
  "Quicksand",
  "Roboto Mono",
  "Roboto",
];
